.flake8
.github/workflows/lint.yml
ingestor/app.py
ingestor/chalicelib/MbtaPerformanceAPI.py
ingestor/chalicelib/bluebikes.py
ingestor/chalicelib/new_trains.py
ingestor/chalicelib/parallel.py
ingestor/chalicelib/s3.py
ingestor/chalicelib/s3_alerts.py
poetry.lock
pyproject.toml

Adding linting CI to follow suit of other apps

Adding Linting CI

---

.vscode/extensions.json
.vscode/settings.json

Make sure vscode works well out of the box

Set up vscode out of the box

---

ingestor/.chalice/config.json
ingestor/.chalice/policy-landing-data.json
ingestor/app.py
ingestor/chalicelib/constants.py
ingestor/chalicelib/landing.py
ingestor/chalicelib/s3.py

Creating a static file in S3 to hold the landing page data because the  slow loading times were driving me insane.
Frontend change coming shortly.

Write landing data to S3 bucket every Monday morning at 5 AM

---

ingestor/chalicelib/constants.py

Forgot to update the API here as well.
The lambdas weren't properly updating speed and service

Missed another /api update

---

ingestor/.chalice/config.json
ingestor/.chalice/policy-time-predictions.json
ingestor/.chalice/resources.json
ingestor/app.py
ingestor/chalicelib/predictions.py

Start ingesting time predictions into dynamo weekly
The data seems to be updated on Saturdays, unsure of the time, so we should read the data on Sundays

Start ingesting prediction accuracy

---

ingestor/.chalice/resources.json

Forgot to add the resource object for the new function

Adding time prediction environment variables

---

.github/workflows/deploy.yml

Adding deploy CI job

---

.flake8
ingestor/chalicelib/ridership/process.py

Pandas is very specific in how it wants to check bools

Fixing ridership ingestion

---

ingestor/chalicelib/daily_speeds.py

Should fix: https://app.datadoghq.com/apm/error-tracking?issueId=94724b98-af5c-11ee-8fa1-da7ad0900002&refresh_mode=sliding&view=spans&from_ts=1705409361356&to_ts=1705412961356&live=true 
Should also  fix the issue seen in slack here: https://transitmatters.slack.com/archives/GSJ6F35DW/p1705319875370099

fix(daily-speeds): data ingestion fails when updating all routes

---

ingestor/app.py
ingestor/chalicelib/agg_speed_tables.py
ingestor/chalicelib/daily_speeds.py

Speed calcs have been broken, this fixes them.
Also backfilled and added a few catches and types to hopefully avoid things breaking down again

Fixing speed calculations

---

ingestor/.chalice/config.json

Increases from 90 second timeout to 150 seconds

Lambdas were timing out a lot, this reduces those chances

---

ingestor/.chalice/config.json
ingestor/.chalice/resources.json

To help with cost tracking and monitoring, adding more tags

Improve tagging of service

---

ingestor/chalicelib/predictions.py

For some reason the link changed, updated to keep getting new data

Fixing predictions link for 2024

---

ingestor/app.py
ingestor/chalicelib/keys.py
ingestor/chalicelib/yankee.py

First PR for ingesting data from the Samsara API provided by Yankee transit. This establishes a lambda that will call the API every minute, persisting the bus positions for which we can detect that the bus is in a shuttle shape in GTFS.

feat: Ingest Yankee Shuttle Travel Times every minute

---

ingestor/chalicelib/yankee.py

fix: s3 import for yankee

---

ingestor/.chalice/policy-yankee.json
ingestor/chalicelib/yankee.py

The lambda wasn't starting without my seeding it with bunk bus positions. Additionally, it needs permission to access the `tm-gtfs` bucket.

fix(yankee): Permission stuff, and allow for starting with no bus positions

---

.github/CODEOWNERS
ingestor/.chalice/config.json
ingestor/.chalice/policy-lamp-ingest.json
ingestor/chalicelib/MbtaPerformanceAPI.py

We need it to have permissions to run

Giving LAMP job permissions

---

.github/CODEOWNERS
ingestor/chalicelib/constants.py

https://github.com/transitmatters/data-ingestion/issues/118

Updating distance to match DD distances

---

ingestor/.chalice/config.json
ingestor/.chalice/policy-bluebikes-calc.json
ingestor/.chalice/policy-bluebikes-store.json
ingestor/chalicelib/bluebikes.py
poetry.lock
pyproject.toml

Ensure all blue bike runs have correct s3 permissions, and catches/throws errors properly

Fix blue bike storage job

---

ingestor/chalicelib/ridership/backfill/manual.py
ingestor/chalicelib/ridership/process.py

Fix south coast rail ridership ingest

---

ingestor/chalicelib/ridership/arcgis.py
ingestor/chalicelib/ridership/box.py

The wrong download function was updated with 4 values, updating the right one and removing the old unused one

Fixing ridership regular ingest

---

ingestor/chalicelib/ridership/arcgis.py

Changed absolute to relative import. Should hopefully fix any packaging issues.

Change sharepoint to relative import
