- .github/CODEOWNERS
- LICENSE
- poetry.lock
- pyproject.toml
Making sure repos are on similar version numbers
- Most importantly getting `pandas` to `1.5.3` which is the last version before 2.0.0
- This should mean we can find any and all deprecation warnings
- Also updates `flake8` and adds `black` (although saves any formatting for a future PR)
- Adds a CODEOWNERS
- Updates boto to the latest
> Updating poetry deps to same versions as dashboard v4

- .github/workflows/lint.yml
- poetry.lock
- pyproject.toml
As we prepare to upgrade our whole stack to python 3.10, allow the CI to run on 3.9 and 3.10
> Allow python 3.10 linting

- ingestor/.chalice/dynamo_tables.json
- ingestor/app.py
- ingestor/chalicelib/gtfs/backfill/main.py
- ingestor/chalicelib/speed_restrictions.py
We want to ingest the MBTA's [speed restrictions data](https://www.arcgis.com/home/item.html?id=d73ed67e4cc84a84b818ea2c5caef696) into the Data Dashboard. Since I looked at this last, they changed the format quite a bit, and there's lots of data now! I've decided it might be better to store this in a database instead of a megabytes-and-growing JSON file, and so I've added a new DynamoDB table for it keyed on `(lineId, date)` and storing the associated slow zones in a `zones` JSON field. Storing this much structured data as unstructured JSON isn't ideal, but we're using Dynamo for so many other things I figured it's a quick way to get this off the ground for now. The lambda rewrites the entire table in a few seconds every day, so it's not a big deal if we want to change that schema.
_Test …
> feature: Ingest MBTA speed restrictions to DynamoDB daily

- ingestor/chalicelib/gtfs/backfill/main.py
- ingestor/chalicelib/gtfs/ingest.py
Even though the Green Line is made of four GTFS `Routes`, we want to treat it as a single route from the perspective of parts of the Data Dashboard. This PR hacks something like that into place so we can query `TripCounts` for `routeId="Green"` and get merged totals.
I'm realizing that, long term, we may want to do this for more than just GL — the MBTA also aggregates some bus routes into lines.
_Test plan:_
Fill `ingestor/chalicelib/gtfs/backfill/.env` with some parameters:
```env
BACKFILL_START_DATE=2016-01-01
BACKFILL_END_DATE=2023-07-05
LOCAL_ARCHIVE_PATH=/path/to/a/folder/for/your/feeds
```
Then run the backfill:
```sh
poetry shell
python -m ingestor.chalicelib.gtfs.backfill.main
```
> feature: Merge GL trip counts into single key

- ingestor/chalicelib/gtfs/ingest.py
- ingestor/chalicelib/gtfs/models.py
- ingestor/chalicelib/gtfs/utils.py
(Actually, service minutes)
_Test plan:_
Run the following:
```
poetry shell
python -m ingestor.chalicelib.gtfs.backfill.main
```
Verify that plausible service minute counts are appearing in the `TripCounts` table in DynamoDB
> feature: Count service hours in TripCounts

- ingestor/.chalice/policy-landing-data.json
We don't have the correct distribution IDs for the landing page data
> Fixing invalidations for v4 prod

- ingestor/app.py
- ingestor/chalicelib/speed_restrictions.py
We have recently been failing to ingest all data on MBTA speed restrictions. It looks like we're running out of memory on the lambdas, and I'm guessing that's because right now this function re-ingests _all_ speed restrictions ever, which we don't need to do. So I've added a `max_lookback_months` parameter that we can use to tell it not to ingest data from months and months ago. I'm hoping this fixes the issue.
We use `max_lookback_months=2` because sometimes they're a little delayed in getting this data up.
> fix: Reduce duplicated work in speed_restrictions ingestor to save memory

- .vscode/settings.json
- ingestor/.chalice/policy-delivered-trip-metrics-daily.json
- ingestor/.chalice/resources.json
- ingestor/app.py
- ingestor/chalicelib/constants.py
- ingestor/chalicelib/daily_speeds.py
- ingestor/chalicelib/stations.py
- ingestor/chalicelib/trip_metrics/__init__.py
- ingestor/chalicelib/trip_metrics/backfill.py
- ingestor/chalicelib/trip_metrics/ingest.py
- ingestor/chalicelib/trip_metrics/types.py
- poetry.lock
- pyproject.toml
This PR adds a `DeliveredTripMetricsExtended` table which will give us good estimates of total delivered service hours. Like `DeliveredTripMetrics`, it stores data from `/api/aggregate/traveltimes2` to get a per-line, per-day snapshot of end-to-end travel time performance. Unlike that table it:
- Separately tracks travel time by direction of travel (`0`, `1`)
- Stores values for trips that are `inclusive` of terminals (Alewife->Ashmont) and `exclusive` of them (Davis->Shawmut)
In other words, every day we'll query these trips as a snapshot `line-red-a`:
- Alewife->Ashmont `(0, inclusive)`
- Ashmont->Alewife `(1, inclusive)`
- Davis->Shawmut `(0, exclusive)`
- Shawmut->Davis `(1, exclusive)`
Since we're storing all the provided statistics for all of these trips (count, mean, std, …
> feature: Ingest more detailed trip metrics

- .gitignore
- ingestor/.chalice/config.json
- ingestor/.chalice/policy-trip-metrics.json
Oops, in #53 I forgot to add a policy file for the new lambda, which means that it wasn't running(!) and also it's preventing further deploys. This fixes that.
_Test plan:_
I ran `deploy.sh` locally and verified that it works now.
> fix: Add policy file for `update_trip_metrics`

- ingestor/chalicelib/constants.py
- ingestor/chalicelib/daily_speeds.py
Fixing https://app.datadoghq.com/apm/error-tracking/issue/be77ad6e-b48b-11ee-ad0d-da7ad0900002?query=env%3Aprod%20service%3Aingestor&refresh_mode=sliding&view=spans&from_ts=1705421607834&to_ts=1705422492193&live=true
We were trying to compare datetime with date
Now resolving this issue and adding type hints to make sure this is more likely avoided in the future
> Fixing date comparisons

- ingestor/.chalice/config.json
- ingestor/.chalice/resources.json
- ingestor/app.py
I didn't realize that the name in `config.json` for chalice had to match up with the name of the lambda, and the error message the package gave wasn't super helpful 😅
> fix(yankee): fix the cloudformation for yankee lambda

- ingestor/.chalice/resources.json
Apparently adding a resource for my lambda to `resources.json` wasnt necessary. I'm guessing the lambdas that are in there are only there to account for what we created before we started using CloudFormation? Anyway, here's the diff between the manual resource and what chalice is creating.
```
"UpdateYankeeShuttles": {
"Type": "AWS::Serverless::Function",
"Properties": {
"Runtime": "python3.11",
"Handler": "app.update_yankee_shuttles",
"CodeUri": "./deployment.zip",
"Tags": {
"service": "ingestor",
"env": "prod",
"aws-chalice": "version=1.31.0:stage=prod:app=ingestor"
},
"Tracing": "PassThrough",
"Timeout": 900,
"MemorySize": 128,
"Environment": {
"Variables": {
"DD_SITE": "datadoghq.com",
"DD_ENV": "prod",
"DD_SERVICE": "ingestor",
"DD_TRACE_ENABLED": "true"
}
},
"Role": {
"Fn::GetAtt": …
```
> fix(yankee): remove unnecessary yankee function resource

- ingestor/chalicelib/yankee.py
Previously the lambda was taking >900s to run. This is likely because it was building a GTFS SQLite db locally everytime, since there was a GTFS feed that hadn't been ingested by our GTFS lambda and added to the `tm-gtfs` S3 bucket. This change should force the yankee lambda to never build the SQLite db locally
> fix(yankee): Improve timeouts by never locally building GTFS SQLite db

- .gitignore
- ingestor/app.py
- ingestor/chalicelib/s3.py
- ingestor/chalicelib/trip_metrics/backfill.py
Ensure we ingest all GTFS feeds
7 day lookback and moves the run 1 hour later in the day to ensure we catch it
> Ensure GTFS ingest

- ingestor/chalicelib/constants.py
- ingestor/chalicelib/landing.py
After we can merge https://github.com/transitmatters/t-performance-dash/pull/1001 we should have ridership data ready to go on the landing page
> Adding commuter rail ridership to the landing page

- ingestor/chalicelib/speed_restrictions.py
The speed restrictions ingestor was failing on filepaths that included a parent directory, e.g.
```
Daily/2024-05_Speed_Restrictions_By_Day.csv
```
The zip structure must have changed. This is a quick fix to make sure we're parsing these paths correctly.
> fix: Update filename parsing for speed restrictions

- ingestor/chalicelib/bluebikes.py
- ingestor/chalicelib/ridership/arcgis.py
- ingestor/chalicelib/ridership/backfill/manual.py
- ingestor/chalicelib/ridership/config.py
- ingestor/chalicelib/ridership/ingest.py
- ingestor/chalicelib/ridership/process.py
The ridership data from ARCGIS requires an update the cache periodically. We should send the cache request before we process it, so that we don't need any manual intervention going forward
> Update ridership cache

- ingestor/app.py
`update_service_ridership_dashboard` was missing an `event` param, lambda won't trigger without it 🥲
> add missing event param to SRD lambda trigger

- ingestor/chalicelib/speed_restrictions.py
Mattapan speed restrictions are recorded as "Red Line" restrictions
> Support Mattapan speed restrictions

- ingestor/TestSharepoint.py
- ingestor/chalicelib/ridership/arcgis.py
- ingestor/chalicelib/ridership/sharepoint.py
This adds support for downloading data from the MBTA Sharepoint links. I'd like to clean this up and add the following before submitting for review. 
1. Ability for users to "List" the files available for Download or return a list to download bulk files if needed
2.  Un-hardcode the SharePoint link values to make this more universally usable 
3. De-duplicate main and fetch_sharepoint_file functions
4. Potentially convert some aspects of this to a class to prevent unnecessary repeat API calls to parse links. I.e some of the following information could be stored within the class.
5. Convert print statements to proper logging 
6. Consolidate logic as needed. 
`[Folder] downloadable data for public - 0 bytes
[Folder] CSVs for public download - 0 bytes
[Folder] Archive - 0 bytes
[File] …
> Add sharepoint support
